spring.application.name=food
spring.devtools.restart.enabled=false
server.port=9090

#mongodb configuration
#spring.data.mongodb.uri=mongodb://localhost:27017/foodies
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=test


#aws s3 configuration
aws.access.key=${AWS_ACCESS_KEY}
aws.secret.key=${AWS_SECRET_KEY}
aws.region=ap-southeast-2
aws.s3.bucketname=foodies-foods17

jwt.secret.key=xP8@L#4NQ7V2mJ8D6R0K!S4EHWZCYaTg

razorpay_key=${RAZORPAY_KEY}
razorpay_secret=${RAZORPAY_SECRET}